repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
    - id: go-mod-tidy
    - id: go-vet-repo-mod
    - id: go-staticcheck-repo-mod
    - id: golangci-lint-mod
